### ISSUE TITLE
放在循环块中输出html报错

### ISSUE THREAD

**Issue by cuining-cn** [draco1023/poi-tl-ext#26]
Exception in thread "main" com.deepoove.poi.exception.RenderException: Unable to render template {{synopsis}}

模板是这样写的：
{{?list}}
	{{synopsis}}
        {{description}}
{{/list}}

调用代码是这样的：
HashMap<String, Object> params = new HashMap<>();
params.put("list",list);
HtmlRenderPolicy htmlRenderPolicy = new HtmlRenderPolicy();
        Configure configure = Configure.builder()
                .bind("synopsis", htmlRenderPolicy)
                .bind("description", htmlRenderPolicy)
                .build();
XWPFTemplate template = XWPFTemplate.compile("d:/file/test.docx", configure).render(params);

其中synopsis和description 是实体中的两个字段，对应两段html。
html代码段的内容直接输出正常，放在循环块中输出就会报最下面的错误信息：
Exception in thread "main" com.deepoove.poi.exception.RenderException: Unable to render template {{synopsis}}
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:83)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:76)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:67)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:80)
	at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
	at com.deepoove.poi.render.processor.IterableProcessor.lambda$handleIterable$0(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.EnvIterator.foreach(EnvIterator.java:33)
	at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:48)
	at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:223)
	at com.sailing.evaluation.test.PoitlTest.charts(PoitlTest.java:91)
	at com.sailing.evaluation.test.PoitlTest.main(PoitlTest.java:96)
Caused by: org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRImpl.getDelTextArray(Unknown Source)
	at org.apache.poi.xwpf.usermodel.XWPFParagraph.getText(XWPFParagraph.java:201)
	at com.deepoove.poi.util.ParagraphUtils.trimLine(ParagraphUtils.java:28)
	at com.deepoove.poi.xwpf.BodyContainer.clearPlaceholder(BodyContainer.java:211)
	at com.deepoove.poi.policy.AbstractRenderPolicy.clearPlaceholder(AbstractRenderPolicy.java:105)
	at org.ddr.poi.html.HtmlRenderPolicy.afterRender(HtmlRenderPolicy.java:340)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:63)
	... 26 more

**Comment by cuining-cn** [comment]
反复折腾发现要输出html的word模板中的变量标签前面不能有空格，有空格就会报错
比如这样就会报错：
{{?list}}
    {{synopsis}}
    {{description}}
{{/list}}
这样就不会报错：
{{?list}}
{{synopsis}}
{{description}}
{{/list}}

**Comment by draco1023** [comment]
> 反复折腾发现要输出html的word模板中的变量标签前面不能有空格，有空格就会报错 比如这样就会报错： {{?list}} {{synopsis}} {{description}} {{/list}} 这样就不会报错： {{?list}} {{synopsis}} {{description}} {{/list}}

没看出有什么区别，问题是已经解决了吗，如果解决了请 Close issue

**Comment by cuining-cn** [comment]
这里发帖子好像不能有空格，我用[空格]代表一个空格
{{?list}}
[空格][空格]{{synopsis}}
[空格][空格]{{description}}
{{/list}}
模板里这样设置就会报那个错，算是一个小bug，但是前面不加空格是没有问题的。目前这个问题，我是把前面的空格删掉后正常了，可以算我的问题已经解决了。

**Comment by draco1023** [comment]
> 这里发帖子好像不能有空格，我用[空格]代表一个空格 {{?list}} [空格][空格]{{synopsis}} [空格][空格]{{description}} {{/list}} 模板里这样设置就会报那个错，算是一个小bug，但是前面不加空格是没有问题的。目前这个问题，我是把前面的空格删掉后正常了，可以算我的问题已经解决了。

我试了下加空格的模板，没有问题。
