### ISSUE TITLE
渲染失败报错，poi-tl版本1.9.1

### ISSUE THREAD

**Issue by yirenyishi** [draco1023/poi-tl-ext#33]
Caused by: org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRImpl.getDelTextArray(Unknown Source)
	at org.apache.poi.xwpf.usermodel.XWPFParagraph.getText(XWPFParagraph.java:201)
	at com.deepoove.poi.util.ParagraphUtils.trimLine(ParagraphUtils.java:28)
	at com.deepoove.poi.xwpf.BodyContainer.clearPlaceholder(BodyContainer.java:211)
	at com.deepoove.poi.policy.AbstractRenderPolicy.clearPlaceholder(AbstractRenderPolicy.java:105)
	at org.ddr.poi.html.HtmlRenderPolicy.afterRender(HtmlRenderPolicy.java:348)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:63)
	... 115 more

**Comment by draco1023** [comment]
请问用的是本插件的哪个版本，html内容是什么

**Comment by yirenyishi** [comment]
![image](https://user-images.githubusercontent.com/13502471/153803708-50a93b02-3ab0-4a66-9969-c15be7ce3a29.png)
标签对前面不能有内容

**Comment by hujun82589167** [comment]
怎么解决的？
