### ISSUE TITLE
XmlValueDisconnectedException: null

### ISSUE THREAD

**Issue by qyw10456** [draco1023/poi-tl-ext#46]
当我使用插件后
![image](https://user-images.githubusercontent.com/86226719/176652503-0a56fdba-210d-4855-b75c-eb0ee57fa79a.png)
hashMap.put("context", safeTrain.getTrainContext());
提示了这个错误

com.deepoove.poi.exception.RenderException: Unable to render template {{context}}

Caused by: org.apache.xmlbeans.impl.values.XmlValueDisconnectedException: null
	at org.apache.xmlbeans.impl.values.XmlObjectBase.check_orphaned(XmlObjectBase.java:1258)
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRImpl.getDelTextArray(Unknown Source)
	at org.apache.poi.xwpf.usermodel.XWPFParagraph.getText(XWPFParagraph.java:201)
	at com.deepoove.poi.util.ParagraphUtils.trimLine(ParagraphUtils.java:28)
	at com.deepoove.poi.xwpf.CellBodyContainer.clearPlaceholder(CellBodyContainer.java:121)
	at com.deepoove.poi.policy.AbstractRenderPolicy.clearPlaceholder(AbstractRenderPolicy.java:105)
	at org.ddr.poi.html.HtmlRenderPolicy.afterRender(HtmlRenderPolicy.java:367)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:63)
	... 138 common frames omitted

但是我直接渲染文本的话是没有问题的

**Comment by draco1023** [comment]
请提供使用的版本，以及html内容

**Comment by qyw10456** [comment]
版本：0.3.13（报错后我改到了0.3.17，还是一样提示的错误）
html：
`<p>一 相关法规的要求</p>
<p>二 疫情管控</p>
<p>三 复工复产教育</p>
<p>四 新员工三级教育及班组安全教育</p>
<p>五 安全大检查</p>
<p>六 常见的危险行为</p>`

**Comment by qyw10456** [comment]
<p>一 相关法规的要求</p>
<p>二 疫情管控</p>
<p>三 复工复产教育</p>
<p>四 新员工三级教育及班组安全教育</p>
<p>五 安全大检查</p>
<p>六 常见的危险行为</p>

**Comment by qyw10456** [comment]
我在本地写个了demo想重现，却发现无法重现，我裂开了，我直接拿service中的实现方式写的demo，只是对象取值、url路径被我写死了，却不报错误了
[demo(1).zip](https://github.com/draco1023/poi-tl-ext/files/9024658/demo.1.zip)

**Comment by draco1023** [comment]
@qyw10456 从异常信息来看问题没有出现在html的渲染过程中，而是在清理阶段，无法复现故暂不处理

**Comment by qyw10456** [comment]
> @qyw10456从异常信息来看问题没有出现在html的渲染过程中，在收拾阶段，无法复现故暂不处理
[demo (2).zip](https://github.com/draco1023/poi-tl-ext/files/9038301/demo.2.zip)
复现了这个问题了
