### ISSUE TITLE
figure标签不支持float样式

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#58]
**Describe the bug**
figure标签不支持float样式
**HTML content:**
<figure class="image image_resized" style="width:29.37%;float:right"><img src="1.jpg"></figure>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
 0.3.22

**poi-tl version:**
1.11.1

**Additional context**

**Comment by stringutils** [comment]
是不是除了表格之外的float都不支持

**Comment by draco1023** [comment]
看不到你的截图，目前未实现表格以外的float

**Comment by stringutils** [comment]
> 看不到你的截图，目前未实现表格以外的float

裂掉的图大概长这样，《figure》 class="image image_resized" style="width:29.37%;float:right">《img src="1.jpg"》《/figure》；我的想法的像处理块标签的text-align属性那样处理处理float，但是这样也不太严谨

**Comment by draco1023** [comment]
在word里并不是所有元素都可以float的，一般来说只有图片或者形状才会支持。

**Comment by draco1023** [comment]
试试`0.4.1`版本，对`figure`的`float`样式按照`text-align`进行了处理。

**Comment by stringutils** [comment]
我更新到最新的版本试了下，float和text-align可以用了；
但是在表格内插入图片或者嵌套图表时表格显示不太好看，而且嵌套表格内的p标签不换行
```
<figure class="table " style="width:85.2%;">
	<table class="ck-table-resized" style="width:85.2%;">
		<colgroup>
			<col style="width:62.81%;">
				<col style="width:37.19%;">
	</colgroup>
		<tbody>
			<tr>
				<td style="width:62.81%;">
				<figure class="image image_resized" style="width:52.25%;">
					<img src="https://avatars.githubusercontent.com/u/1821583?s=80&v=4">
					</figure>
				</td>
				<td style="width:18.36%;">
					<figure class="table " style="width:100%;">
						<table style="width:100%;">
							<tbody>
								<tr>
									<td colspan="2">&nbsp;</td>
								</tr>
								<tr>
									<td>
										<p>aaa</p>
										<p>bbb</p>
										<p>ccc</p>
									</td>
									<td>&nbsp;</td>
								</tr>
							</tbody>
						</table>
					</figure>
				</td>
			</tr>
		</tbody>
	</table>
</figure>
```
![1667532725304](https://user-images.githubusercontent.com/35484811/199879432-8a995141-f586-459d-9332-7c2e4d506d7a.png)

**Comment by draco1023** [comment]
试试`main`或`poi-t`分支的最新代码，不过不清楚你说的表格显示不好看是个什么概念

**Comment by stringutils** [comment]
我用poi-5最新的代码跑上面那个html片段报这个错：
```
Caused by: java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.remove(Collections.java:1058)
	at org.ddr.poi.html.HtmlRenderContext.removeParagraph(HtmlRenderContext.java:1310)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1242)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1281)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1197)
	at org.ddr.poi.html.HtmlRenderContext.renderDocument(HtmlRenderContext.java:1188)
	at org.ddr.poi.html.HtmlRenderPolicy.doRender(HtmlRenderPolicy.java:160)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:62)
```

**Comment by draco1023** [comment]
poi的API改成了不可修改的列表，更新一下

**Comment by stringutils** [comment]
> poi的API改成了不可修改的列表，更新一下
更新到最新的代码后验证后，这个问题修复了
