### ISSUE TITLE
多线程下报数组越界的异常

### ISSUE THREAD

**Issue by stringutils** [draco1023/poi-tl-ext#64]
**Describe the bug**
多线程下报异常
**HTML content:**
doc文档里只有一行：{{plainContent}}
```
for(int i=0;i<5;i++) {
            new Thread(() -> {
                try {
                    HtmlRenderPolicy htmlRenderPolicy = new HtmlRenderPolicy();
                    Configure configure = Configure.builder()
                            .bind("plainContent", htmlRenderPolicy)
                            .build();
                    Map<String, Object> data = new HashMap<>(2);
                    data.put("plainContent", "<table class=\"table \" style=\"width:85.2%;\"></table>");
                    try (InputStream inputStream = FileUtils.openInputStream(new File("D:\\demo.docx"))) {
                        XWPFTemplate.compile(inputStream, configure)
                                .render(data).writeToFile(System.currentTimeMillis()+"notes_out_1.docx");
                    }catch (Exception e){
                          e.printStackTrace();
                      }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }).start();
        }
```
异常信息如下：
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at com.steadystate.css.parser.SACParserCSS3TokenManager.jjMoveNfa_0(SACParserCSS3TokenManager.java:5189)
	at com.steadystate.css.parser.SACParserCSS3TokenManager.jjMoveStringLiteralDfa0_0(SACParserCSS3TokenManager.java:188)
	at com.steadystate.css.parser.SACParserCSS3TokenManager.getNextToken(SACParserCSS3TokenManager.java:7526)
	at com.steadystate.css.parser.SACParserCSS3.jj_ntk_f(SACParserCSS3.java:4063)
	at com.steadystate.css.parser.SACParserCSS3.styleDeclaration(SACParserCSS3.java:2081)
	at com.steadystate.css.parser.AbstractSACParser.parseStyleDeclaration(AbstractSACParser.java:333)
	at com.steadystate.css.parser.SACParserCSS3.parseStyleDeclaration(SACParserCSS3.java:33)
	at com.steadystate.css.parser.CSSOMParser.parseStyleDeclaration(CSSOMParser.java:162)
	at com.steadystate.css.parser.CSSOMParser.parseStyleDeclaration(CSSOMParser.java:153)
	at org.ddr.poi.html.util.CSSStyleUtils.parse(CSSStyleUtils.java:55)
	at org.ddr.poi.html.HtmlRenderContext.getCssStyleDeclaration(HtmlRenderContext.java:1341)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1164)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1150)
	at org.ddr.poi.html.HtmlRenderContext.renderDocument(HtmlRenderContext.java:1141)
	at org.ddr.poi.html.HtmlRenderPolicy.doRender(HtmlRenderPolicy.java:131)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:62)
```

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
0.4.1-poi5

**poi-tl version:**
1.11.1

**Additional context**

**Comment by draco1023** [comment]
问题出在全局共用了CSS解析器，已经发布`0.4.2`版本。另外在多线程环境下，实际上`HtmlRenderPolicy`是可以共享的。
