### ISSUE TITLE
解析表格报错 No table in stack

### ISSUE THREAD

**Issue by sos233** [draco1023/poi-tl-ext#82]
**Describe the bug**
您好，我这边解析表格时遇到一个报错，麻烦看一下：
com.deepoove.poi.exception.RenderException: Unable to render template {{content}}
2023-08-17 17:33:12,953 INFO  [com.deepoove.poi.render.processor.DelegatePolicy:43] - Start render Template {{content}}, Sign: , policy:HtmlRenderPolicy
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:87)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:69)
	at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:80)
	at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
	at com.deepoove.poi.render.processor.IterableProcessor.lambda$handleIterable$0(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.EnvIterator.foreach(EnvIterator.java:33)
	at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:48)
	at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.process(AbstractIterableProcessor.java:80)
	at com.deepoove.poi.render.processor.IterableProcessor.next(IterableProcessor.java:161)
	at com.deepoove.poi.render.processor.IterableProcessor.lambda$handleIterable$0(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.EnvIterator.foreach(EnvIterator.java:33)
	at com.deepoove.poi.render.processor.IterableProcessor.handleIterable(IterableProcessor.java:93)
	at com.deepoove.poi.render.processor.AbstractIterableProcessor.visit(AbstractIterableProcessor.java:48)
	at com.deepoove.poi.render.processor.IterableProcessor.visit(IterableProcessor.java:50)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:90)
	at com.deepoove.poi.template.IterableTemplate.accept(IterableTemplate.java:32)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:209)
...
Caused by: java.lang.IllegalStateException: No table in stack
	at org.ddr.poi.html.HtmlRenderContext.getClosestTable(HtmlRenderContext.java:513)
	at org.ddr.poi.html.tag.TableCellRenderer.renderStart(TableCellRenderer.java:55)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1307)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1230)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1314)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1230)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1314)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1230)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1314)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1230)
	at org.ddr.poi.html.HtmlRenderContext.renderElement(HtmlRenderContext.java:1314)
	at org.ddr.poi.html.HtmlRenderContext.renderNode(HtmlRenderContext.java:1230)
	at org.ddr.poi.html.HtmlRenderContext.renderDocument(HtmlRenderContext.java:1221)
	at org.ddr.poi.html.HtmlRenderPolicy.doRender(HtmlRenderPolicy.java:160)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:66)

**HTML content:**

```html
<div style="white-space: pre;" data-zone-id="0" data-line-index="1" data-line="true">
 <table style="border-collapse: collapse; width: 680px; height: 169px;" border="1">
  <tbody>
   <tr style="height: 169px;">
    <td style="width: auto; height: auto;">
     <p style="text-align: center;">a</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">b</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">c</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">e</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">f</p></td>
   </tr>
  </tbody>
 </table>
</div>
``` 

<div style="white-space: pre;" data-zone-id="0" data-line-index="1" data-line="true">
 <table style="border-collapse: collapse; width: 680px; height: 169px;" border="1">
  <tbody>
   <tr style="height: 169px;">
    <td style="width: auto; height: auto;">
     <p style="text-align: center;">a</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">b</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">c</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">e</p></td>
    <td style="width: auto; height: auto;">
     <p></p>
     <p style="text-align: center;">f</p></td>
   </tr>
  </tbody>
 </table>
</div>

**Expected behavior**

**Screenshots**

**poi-tl-ext version:**
0.4.5-poi5

**poi-tl version:**
1.12.1

**Additional context**

**Comment by sos233** [comment]
我发现是父级div style中"white-space: pre;"造成影响了，删除以后暂时不会报错了

**Comment by draco1023** [comment]
请使用`0.4.6-poi5`版本
