### ISSUE TITLE
页面有如下table时候，解析失败

### ISSUE THREAD

**Issue by wangdy0909** [draco1023/poi-tl-ext#9]
页面有如下table时候，解析失败
<table>
    <tr>
        <td>
            1
        </td>
        <td>
            2
        </td>
        <td>
            3
        </td>
    </tr>
</table>

![image](https://user-images.githubusercontent.com/26474273/122191597-77e04e00-cec5-11eb-994d-3067f535f7fe.png)

报如下错误：
Caused by: java.lang.UnsupportedOperationException: Invalid CSS length
	at org.ddr.poi.html.HtmlRenderContext.lengthToEMU(HtmlRenderContext.java:665)
	at org.ddr.poi.html.tag.TableRenderer.renderStart(TableRenderer.java:79)
	at org.ddr.poi.html.HtmlRenderPolicy.renderElement(HtmlRenderPolicy.java:225)
	at org.ddr.poi.html.HtmlRenderPolicy.renderNode(HtmlRenderPolicy.java:152)
	at org.ddr.poi.html.HtmlRenderPolicy.doRender(HtmlRenderPolicy.java:143)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:62)

**Comment by draco1023** [comment]
已修复，事实上应尽量避免使用这样的表格，没有任何样式的表格呈现时取决于浏览器的默认实现，当前的代码实现呈现在word中奖是没有任何边框的
